export const CONTACT = {
  email: "mynri360@gmail.com",
  phone: "9505163369",
  phoneIntl: "+919505163369",
  whatsapp: "919505163369",
  instagram: "mynri360",
  instagramUrl: "https://instagram.com/mynri360",
  hours: "Mon – Sun · 24×7 assistance across time zones",
  locationName: "Rajahmundry",
  address: "Happy Street, Rajahmundry",
  mapUrl: "https://www.google.com/search?q=happy+street+rajahmundry&oq=happy+street&gs_lcrp=EgZjaHJvbWUqBwgBEAAYgAQyBggAEEUYOTIHCAEQABiABDIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIHCAcQABiABDIHCAgQABiABDIHCAkQABiABNIBCTUxODZqMGoxNagCCLACAfEFSkxI7TgTTCo&sourceid=chrome&source=chrome.rb&ie=UTF-8",
};

export const SERVICE_OPTIONS = [
  "Senior Citizen Care",
  "Real Estate",
  "Property Management",
  "Legal Support",
  "Documentation",
  "PAN",
  "Aadhaar",
  "Tax Filing",
  "Banking",
  "Construction",
  "Home Maintenance",
  "Investments",
  "Courier",
  "Visa Support",
  "Travel Planning",
  "Vacation Planning",
  "Self Drive Car",
  "Indian Sweets",
  "Snacks",
  "Pickles",
  "Powders",
  "Concierge",
  "Other",
];

export type Service = {
  slug: string;
  title: string;
  category: string;
  icon: string;
  blurb: string;
  benefits: string[];
  documents: string[];
  timeline: string;
  imageUrl?: string;
};

export const SERVICES: Service[] = [
  {
    slug: "senior-citizen-care",
    title: "Senior Citizen Care",
    category: "Family & Care",
    icon: "HeartHandshake",
    blurb: "Scheduled visits, medical escorts, groceries and daily wellbeing checks for your parents.",
    benefits: ["Verified caregivers", "Medical appointment escort", "Weekly video reports", "Emergency response"],
    documents: ["ID proof of parent", "Doctor prescriptions", "Emergency contacts"],
    timeline: "Onboarding in 48 hours",
  },
  {
    slug: "family-assistance",
    title: "Family Assistance",
    category: "Family & Care",
    icon: "Users",
    blurb: "A dependable local presence for school admissions, functions, festivals and emergencies.",
    benefits: ["Dedicated relationship manager", "Event coordination", "On-ground errands", "24×7 escalation"],
    documents: ["Family details", "Authorisation letter"],
    timeline: "Same-week deployment",
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    category: "Property",
    icon: "Building2",
    blurb: "Buy, sell or lease Indian property with due diligence, valuation and end-to-end paperwork.",
    benefits: ["Title verification", "Market valuation", "Virtual site tours", "Registration support"],
    documents: ["Passport / OCI", "PAN card", "Title deed", "Power of Attorney"],
    timeline: "30 – 90 days typical",
  },
  {
    slug: "property-management",
    title: "Property Management",
    category: "Property",
    icon: "KeyRound",
    blurb: "Tenant sourcing, rent collection, inspections and statutory dues handled monthly.",
    benefits: ["Verified tenants", "Rent remittance", "Quarterly inspections", "Tax & dues payment"],
    documents: ["Ownership proof", "Bank mandate"],
    timeline: "Live in 7 days",
  },
  {
    slug: "construction",
    title: "Construction",
    category: "Property",
    icon: "HardHat",
    blurb: "Architect coordination, contractor vetting and milestone-linked progress reporting.",
    benefits: ["Vetted contractors", "Milestone audits", "Weekly photo updates", "Budget control"],
    documents: ["Plot documents", "Approved plan"],
    timeline: "Project based",
  },
  {
    slug: "home-maintenance",
    title: "Home Maintenance",
    category: "Property",
    icon: "Wrench",
    blurb: "Deep cleaning, repairs, painting and pre-arrival readiness before your India visit.",
    benefits: ["Trusted vendors", "Before / after proof", "Arrival readiness", "Annual plans"],
    documents: ["Property address", "Access instructions"],
    timeline: "3 – 10 days",
  },
  {
    slug: "legal-services",
    title: "Legal Services",
    category: "Legal & Documentation",
    icon: "Scale",
    blurb: "Advocates for property disputes, succession, POA drafting and court representation.",
    benefits: ["Empanelled advocates", "Case tracking", "POA drafting", "Notary & attestation"],
    documents: ["Case papers", "ID proof", "POA draft"],
    timeline: "Advisory in 72 hours",
  },
  {
    slug: "documentation",
    title: "Documentation",
    category: "Legal & Documentation",
    icon: "FileText",
    blurb: "Certificates, apostille, attestation and record corrections without a trip to India.",
    benefits: ["Apostille & attestation", "Record correction", "Courier included", "Status tracking"],
    documents: ["Existing certificates", "Passport copy"],
    timeline: "1 – 4 weeks",
  },
  {
    slug: "pan-application",
    title: "PAN Application",
    category: "Legal & Documentation",
    icon: "IdCard",
    blurb: "New PAN, corrections and reprints for NRIs with overseas address support.",
    benefits: ["Form 49AA handled", "Overseas dispatch", "Correction support", "e-PAN delivery"],
    documents: ["Passport", "Overseas address proof", "Photograph"],
    timeline: "10 – 20 days",
  },
  {
    slug: "aadhaar-assistance",
    title: "Aadhaar Assistance",
    category: "Legal & Documentation",
    icon: "Fingerprint",
    blurb: "Enrolment appointments, updates and biometric scheduling during your India visit.",
    benefits: ["Appointment booking", "Detail updates", "Escort support", "Follow-up tracking"],
    documents: ["Passport", "Visa / OCI", "Proof of address"],
    timeline: "Visit dependent",
  },
  {
    slug: "tax-filing",
    title: "Tax Filing",
    category: "Finance",
    icon: "Calculator",
    blurb: "NRI income tax returns, DTAA relief, capital gains and lower deduction certificates.",
    benefits: ["Chartered accountants", "DTAA optimisation", "Capital gains planning", "Notice handling"],
    documents: ["Form 16 / 26AS", "Bank statements", "Sale deeds"],
    timeline: "5 – 15 days",
  },
  {
    slug: "banking-assistance",
    title: "Banking Assistance",
    category: "Finance",
    icon: "Landmark",
    blurb: "NRE / NRO account opening, KYC updates, repatriation and locker management.",
    benefits: ["Account opening", "KYC refresh", "Repatriation (15CA/CB)", "Cheque & locker support"],
    documents: ["Passport", "Visa", "Address proof", "PAN"],
    timeline: "7 – 21 days",
  },
  {
    slug: "investments",
    title: "Investments",
    category: "Finance",
    icon: "TrendingUp",
    blurb: "Mutual funds, bonds, fixed deposits and portfolio reviews aligned to NRI regulations.",
    benefits: ["SEBI-registered partners", "FEMA compliant", "Portfolio reviews", "Repatriation planning"],
    documents: ["PAN", "NRE / NRO details", "KYC documents"],
    timeline: "Advisory in 72 hours",
  },
  {
    slug: "courier-support",
    title: "Courier Support",
    category: "Concierge",
    icon: "Package",
    blurb: "Door-to-door document and gift courier between India and your country of residence.",
    benefits: ["Insured shipping", "Customs guidance", "Live tracking", "Doorstep pickup"],
    documents: ["Shipping address", "Contents declaration"],
    timeline: "3 – 8 days",
  },
  {
    slug: "sponsor-visa-support",
    title: "Sponsor Visa Support",
    category: "Travel",
    icon: "Plane",
    blurb: "Invitation letters, sponsorship paperwork and appointment support for family visits.",
    benefits: ["Document checklist", "Form filling", "Appointment booking", "Interview prep"],
    documents: ["Passports", "Invitation details", "Financial proof"],
    timeline: "2 – 6 weeks",
  },
  {
    slug: "travel-planning",
    title: "Travel Planning",
    category: "Travel",
    icon: "Map",
    blurb: "Flights, airport pickups, hotels and full itineraries for you and visiting family.",
    benefits: ["Airport assistance", "Curated stays", "Local transport", "24×7 travel desk"],
    documents: ["Travel dates", "Passenger details"],
    timeline: "Instant to 5 days",
  },
  {
    slug: "vacation-planning",
    title: "Vacation Planning",
    category: "Travel",
    icon: "Palmtree",
    blurb: "Heritage, spiritual and leisure itineraries designed around your India holiday.",
    benefits: ["Custom itineraries", "Guided experiences", "Family friendly", "Premium stays"],
    documents: ["Preferred dates", "Group size"],
    timeline: "3 – 7 days to plan",
  },
  {
    slug: "self-drive-car-rental",
    title: "Self Drive Car Rental",
    category: "Travel",
    icon: "Car",
    blurb: "Sanitised, insured self-drive cars delivered to your airport or doorstep.",
    benefits: ["Airport delivery", "Insured vehicles", "Flexible duration", "Roadside support"],
    documents: ["Driving licence", "Passport copy"],
    timeline: "24 hours notice",
  },
  {
    slug: "traditional-sweets",
    title: "Traditional Sweets",
    category: "Taste of India",
    icon: "Cake",
    blurb: "Authentic regional sweets prepared fresh and shipped worldwide with care.",
    benefits: ["Fresh preparation", "Hygienic packing", "Global shipping", "Festival specials"],
    documents: ["Delivery address"],
    timeline: "5 – 10 days",
  },
  {
    slug: "indian-snacks",
    title: "Indian Snacks",
    category: "Taste of India",
    icon: "Cookie",
    blurb: "Homestyle savouries and namkeen packed to travel — the taste you grew up with.",
    benefits: ["Homestyle recipes", "Vacuum packing", "Custom hampers", "Bulk orders"],
    documents: ["Delivery address"],
    timeline: "5 – 10 days",
  },
  {
    slug: "pickles",
    title: "Pickles",
    category: "Taste of India",
    icon: "Soup",
    blurb: "Traditional regional pickles, sun-cured and sealed for international delivery.",
    benefits: ["Regional varieties", "Leak-proof packing", "No preservatives option", "Seasonal batches"],
    documents: ["Delivery address"],
    timeline: "5 – 12 days",
  },
  {
    slug: "homemade-powders",
    title: "Homemade Powders",
    category: "Taste of India",
    icon: "Utensils",
    blurb: "Podis, masalas and health mixes ground fresh to your family recipe.",
    benefits: ["Custom recipes", "Fresh grinding", "Airtight packing", "Repeat subscriptions"],
    documents: ["Recipe preferences", "Delivery address"],
    timeline: "5 – 12 days",
  },
  {
    slug: "concierge-services",
    title: "Concierge Services",
    category: "Concierge",
    icon: "Sparkles",
    blurb: "Anything else you need in India — one request, one manager, one accountable team.",
    benefits: ["Single point of contact", "Custom requests", "Priority handling", "Transparent quotes"],
    documents: ["Request brief"],
    timeline: "Response in 4 hours",
  },
];

export const WHY_US = [
  { title: "Experienced Team", desc: "Advocates, CAs and managers with decades of NRI casework.", icon: "Award" },
  { title: "Fast Turnaround", desc: "Assigned within hours, first update within a working day.", icon: "Zap" },
  { title: "Trusted Professionals", desc: "Every partner background-verified before onboarding.", icon: "ShieldCheck" },
  { title: "Transparent Process", desc: "Written scope, fixed quotes, no surprise charges.", icon: "Eye" },
  { title: "Affordable Pricing", desc: "Fair, published fees benchmarked to local rates.", icon: "BadgeIndianRupee" },
  { title: "24×7 Support", desc: "Time-zone aware support across every continent.", icon: "Clock" },
  { title: "Global Reach", desc: "Serving NRIs in 10+ countries and 100+ Indian cities.", icon: "Globe2" },
  { title: "Dedicated Assistance", desc: "One relationship manager owns your case end to end.", icon: "UserCheck" },
];

export const PROCESS = [
  { step: "01", title: "Choose Service", desc: "Pick what you need from 20+ NRI services." },
  { step: "02", title: "Talk to Expert", desc: "A specialist calls you at your preferred time." },
  { step: "03", title: "Documentation", desc: "We share a checklist and collect everything digitally." },
  { step: "04", title: "Execution", desc: "Our on-ground team performs the work in India." },
  { step: "05", title: "Completion", desc: "Deliverables, receipts and reports handed over." },
  { step: "06", title: "Customer Satisfaction", desc: "Follow-up review and ongoing support." },
];

export const STATS = [
  { value: 5000, suffix: "+", label: "Happy NRIs" },
  { value: 50, suffix: "+", label: "Professional Partners" },
  { value: 100, suffix: "+", label: "Cities Covered" },
  { value: 24, suffix: "×7", label: "Support" },
  { value: 99, suffix: "%", label: "Customer Satisfaction" },
];

export const TESTIMONIALS = [
  {
    name: "Ramesh Iyer",
    role: "Software Director",
    country: "United States",
    flag: "🇺🇸",
    rating: 5,
    quote:
      "They managed my father's medical appointments and our Chennai property for two years. I finally sleep peacefully 12,000 km away.",
  },
  {
    name: "Priya Menon",
    role: "Consultant",
    country: "United Kingdom",
    flag: "🇬🇧",
    rating: 5,
    quote:
      "Property sale, POA, tax filing and repatriation — all coordinated by one manager. The transparency was exceptional.",
  },
  {
    name: "Arjun Sharma",
    role: "Entrepreneur",
    country: "UAE",
    flag: "🇦🇪",
    rating: 5,
    quote:
      "My Hyderabad villa construction was tracked with weekly photos and audited bills. Zero surprises, zero stress.",
  },
  {
    name: "Meera Nair",
    role: "Physician",
    country: "Canada",
    flag: "🇨🇦",
    rating: 5,
    quote:
      "From Aadhaar updates to my mother's monthly groceries, everything is handled. It feels like family, not a vendor.",
  },
  {
    name: "Vikram Rao",
    role: "Finance Lead",
    country: "Singapore",
    flag: "🇸🇬",
    rating: 5,
    quote: "NRE account, DTAA filing and mutual fund KYC completed in three weeks without a single trip to India.",
  },
  {
    name: "Anita Desai",
    role: "Architect",
    country: "Australia",
    flag: "🇦🇺",
    rating: 5,
    quote: "The concierge team shipped festival sweets to Melbourne and arranged our entire Kerala holiday. Flawless.",
  },
];

export const COUNTRIES = [
  { name: "USA", flag: "🇺🇸", x: 22, y: 38 },
  { name: "Canada", flag: "🇨🇦", x: 21, y: 26 },
  { name: "UK", flag: "🇬🇧", x: 46, y: 27 },
  { name: "Germany", flag: "🇩🇪", x: 50, y: 30 },
  { name: "Europe", flag: "🇪🇺", x: 48.5, y: 34 },
  { name: "Saudi Arabia", flag: "🇸🇦", x: 57, y: 46 },
  { name: "Qatar", flag: "🇶🇦", x: 59.5, y: 45 },
  { name: "Dubai", flag: "🇦🇪", x: 61, y: 47 },
  { name: "Singapore", flag: "🇸🇬", x: 74, y: 58 },
  { name: "Australia", flag: "🇦🇺", x: 82, y: 74 },
];

export type MapHotspot = {
  id: string;
  name: string;
  code: string;
  flag: string;
  x: number;
  y: number;
  nriCount: string;
  timezone: string;
  timeOffset: number;
  popularServices: string[];
  isHub?: boolean;
};

export const MAP_HOTSPOTS: MapHotspot[] = [
  {
    id: "india",
    name: "India (Operational Hub)",
    code: "in",
    flag: "🇮🇳",
    x: 64.5,
    y: 54.2,
    nriCount: "100+ Cities Network",
    timezone: "IST (UTC +5:30)",
    timeOffset: 5.5,
    popularServices: ["Senior Care", "Property Diligence", "Legal POA", "Tax & Repatriation"],
    isHub: true,
  },
  {
    id: "usa",
    name: "United States",
    code: "us",
    flag: "🇺🇸",
    x: 17.5,
    y: 45.5,
    nriCount: "2,100+ NRIs Served",
    timezone: "EST / PST",
    timeOffset: -5,
    popularServices: ["Parent Senior Care", "Property Management", "PAN & Tax Filing"],
  },
  {
    id: "canada",
    name: "Canada",
    code: "ca",
    flag: "🇨🇦",
    x: 18.5,
    y: 38.0,
    nriCount: "950+ NRIs Served",
    timezone: "EST / MST",
    timeOffset: -5,
    popularServices: ["Aadhaar Appointments", "Property Sale", "Financial KYC"],
  },
  {
    id: "brazil",
    name: "Brazil",
    code: "br",
    flag: "🇧🇷",
    x: 31.0,
    y: 65.5,
    nriCount: "150+ NRIs Served",
    timezone: "BRT (UTC -3)",
    timeOffset: -3,
    popularServices: ["Document Attestation", "Concierge Services"],
  },
  {
    id: "uk",
    name: "United Kingdom",
    code: "gb",
    flag: "🇬🇧",
    x: 43.0,
    y: 34.2,
    nriCount: "800+ NRIs Served",
    timezone: "GMT / BST",
    timeOffset: 0,
    popularServices: ["Property Management", "Legal Disputes", "Inheritance"],
  },
  {
    id: "germany",
    name: "Germany",
    code: "de",
    flag: "🇩🇪",
    x: 52.0,
    y: 37.0,
    nriCount: "420+ NRIs Served",
    timezone: "CET (UTC +1)",
    timeOffset: 1,
    popularServices: ["Tax DTAA Filing", "Bank Account Opening", "Legal Diligence"],
  },
  {
    id: "france",
    name: "France",
    code: "fr",
    flag: "🇫🇷",
    x: 44.5,
    y: 42.0,
    nriCount: "310+ NRIs Served",
    timezone: "CET (UTC +1)",
    timeOffset: 1,
    popularServices: ["Apostille Services", "Family Assistance"],
  },
  {
    id: "uae",
    name: "UAE & Gulf",
    code: "ae",
    flag: "🇦🇪",
    x: 55.0,
    y: 53.5,
    nriCount: "1,200+ NRIs Served",
    timezone: "GST (UTC +4)",
    timeOffset: 4,
    popularServices: ["Real Estate Purchase", "Construction Audits", "Fast Courier"],
  },
  {
    id: "south-africa",
    name: "South Africa",
    code: "za",
    flag: "🇿🇦",
    x: 53.0,
    y: 73.0,
    nriCount: "250+ NRIs Served",
    timezone: "SAST (UTC +2)",
    timeOffset: 2,
    popularServices: ["Documentation", "Parent Wellbeing Checks"],
  },
  {
    id: "russia",
    name: "Russia",
    code: "ru",
    flag: "🇷🇺",
    x: 75.0,
    y: 35.5,
    nriCount: "180+ NRIs Served",
    timezone: "MSK (UTC +3)",
    timeOffset: 3,
    popularServices: ["Documentation Attestation", "Courier Services"],
  },
  {
    id: "china",
    name: "China",
    code: "cn",
    flag: "🇨🇳",
    x: 80.0,
    y: 44.5,
    nriCount: "320+ NRIs Served",
    timezone: "CST (UTC +8)",
    timeOffset: 8,
    popularServices: ["Financial Repatriation", "Property Management"],
  },
  {
    id: "singapore",
    name: "Singapore",
    code: "sg",
    flag: "🇸🇬",
    x: 77.0,
    y: 61.0,
    nriCount: "650+ NRIs Served",
    timezone: "SGT (UTC +8)",
    timeOffset: 8,
    popularServices: ["NRE / NRO Banking", "Mutual Fund KYC", "Vacation Planning"],
  },
  {
    id: "australia",
    name: "Australia",
    code: "au",
    flag: "🇦🇺",
    x: 84.0,
    y: 73.0,
    nriCount: "550+ NRIs Served",
    timezone: "AEST (UTC +10)",
    timeOffset: 10,
    popularServices: ["Taste of India Sweets", "Senior Care", "Self Drive Rental"],
  },
];

export const VALUE_PILLARS = [
  {
    title: "TRUSTED",
    subtitle: "Your Trusted Partner in India",
    icon: "ShieldCheck",
    desc: "100% verified legal advocates, chartered accountants, and healthcare professionals bound by legal service contracts.",
    color: "from-amber-500/20 to-orange-500/10 border-amber-500/30",
  },
  {
    title: "PERSONALIZED",
    subtitle: "Tailored Solutions for Every NRI",
    icon: "Users",
    desc: "Dedicated single-point Relationship Manager assigned to own your case from start to final sign-off.",
    color: "from-blue-500/20 to-cyan-500/10 border-blue-500/30",
  },
  {
    title: "GLOBAL REACH",
    subtitle: "Serving NRIs Worldwide",
    icon: "Globe2",
    desc: "Seamless operations across 10+ countries and execution across 100+ cities in India.",
    color: "from-emerald-500/20 to-teal-500/10 border-emerald-500/30",
  },
  {
    title: "24/7 SUPPORT",
    subtitle: "Always Here To Help",
    icon: "Clock",
    desc: "Round-the-clock availability aligned with US, UK, Gulf, and APAC time zones for immediate response.",
    color: "from-amber-400/20 to-yellow-500/10 border-yellow-500/30",
  },
  {
    title: "END TO END SUPPORT",
    subtitle: "From Planning To Completion",
    icon: "Handshake",
    desc: "Complete lifecycle management from initial consultation, document pick-up, execution to physical delivery.",
    color: "from-indigo-500/20 to-purple-500/10 border-indigo-500/30",
  },
  {
    title: "PROFESSIONAL",
    subtitle: "Verified Experts You Can Rely On",
    icon: "Award",
    desc: "Transparent scope, fixed pricing upfront, and regular photo/video evidence progress reports.",
    color: "from-green-500/20 to-emerald-500/10 border-green-500/30",
  },
];

export const FAQS = [
  {
    q: "Do I need to travel to India to use NRI360?",
    a: "In most cases, no. We work through digital documentation and a registered Power of Attorney where legally required, so services like tax filing, property management, banking and documentation are completed while you stay abroad.",
  },
  {
    q: "How are your professionals verified?",
    a: "Every advocate, chartered accountant, contractor and caregiver is background-checked, credential-verified and bound by a service agreement with NRI360 before being assigned to a client.",
  },
  {
    q: "How is pricing decided?",
    a: "You receive a written scope and a fixed quote before any work begins. Government fees and third-party charges are passed through at actuals with receipts.",
  },
  {
    q: "Which countries do you support?",
    a: "We actively serve NRIs in the USA, Canada, UK, Germany, wider Europe, Singapore, UAE, Qatar, Saudi Arabia and Australia, with support scheduled in your local time zone.",
  },
  {
    q: "How quickly will someone contact me?",
    a: "Requests submitted through the website or WhatsApp receive a response within four working hours, and an expert consultation is scheduled within one working day.",
  },
  {
    q: "Is my personal data safe?",
    a: "Documents are shared through secure channels, accessed only by the assigned team, and retained strictly for the duration required to complete your service.",
  },
];

export const INSIGHTS = [
  {
    tag: "Taxation",
    title: "NRI Tax Filing 2026: what changed and what to claim",
    desc: "New reporting thresholds, DTAA relief and capital-gains rules every NRI should review before the deadline.",
    read: "6 min read",
  },
  {
    tag: "Property",
    title: "Buying property in India from abroad — a 9-step checklist",
    desc: "Title diligence, POA drafting, registration and repatriation planning, in the right order.",
    read: "8 min read",
  },
  {
    tag: "Family Care",
    title: "Caring for ageing parents from another time zone",
    desc: "How structured visits, medical escorts and reporting rhythms remove the guesswork.",
    read: "5 min read",
  },
];

export const VALUES = [
  { title: "Integrity", desc: "We say what we will do, then show proof that we did it." },
  { title: "Empathy", desc: "Every case involves a family, not a ticket number." },
  { title: "Precision", desc: "Compliance-grade accuracy on every document we touch." },
  { title: "Speed", desc: "Distance should never mean delay." },
  { title: "Confidentiality", desc: "Your documents and finances stay strictly private." },
  { title: "Accountability", desc: "One named manager owns your outcome." },
];

export const MILESTONES = [
  { year: "2019", title: "The First Request", desc: "Founded to help one family manage their parents' care from Dallas." },
  { year: "2021", title: "Professional Network", desc: "Advocates, CAs and property managers onboarded across South India." },
  { year: "2023", title: "Going Global", desc: "Clients across the USA, UK, UAE, Singapore and Australia." },
  { year: "2024", title: "100+ Cities", desc: "On-ground execution capability extended nationwide." },
  { year: "2026", title: "NRI360 Platform", desc: "One digital front door for every NRI service in India." },
];
